training:
  model_name: 'bilstm'
  learning_rate: 0.8
  epochs: 3
  maxlen: 128
  embedding_dim: 100
preprocessing:
  input_convertor: 'nn_vectorization'
  pretrained_embedding: ./data/glove.twitter.27B.100d.mini.txt
  maxlen: 128
  embedding_dim: 100
